import type { Metadata } from "next";

import "./globals.css";

import { CartProvider } from "./context/CartContext";


export const metadata: Metadata = {
  title: "Micro-Store",
  description: "Generated by create next app",
  icons : {
    icon : './icon.svg'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      
      
    
      <body>
        <CartProvider>
          <div>{children}</div>
        </CartProvider>
      </body>
    </html>
  );
}
